import os

# Base directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Input/Output directories
INPUT_DIR = os.path.join(BASE_DIR, 'data', 'input')
OUTPUT_DIR = os.path.join(BASE_DIR, 'data', 'output')
TEMP_DIR = os.path.join(BASE_DIR, 'temp_processing')

# Ensure directories exist
os.makedirs(INPUT_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Allowed file extensions
ALLOWED_EXTENSIONS = {'.png', '.jpg', '.jpeg', '.pdf'}

# OCR Settings
OCR_LANGUAGES = ['en']
USE_GPU = False  # Set to True if you have CUDA installed

# Country Codes (ISO 3166-1 alpha-3)
# This is a subset. In a real production app, consider loading this from a standard library or full JSON file.
COUNTRY_CODES = [
    {"name": "Afghanistan", "alpha-3": "AFG"},
    {"name": "Albania", "alpha-3": "ALB"},
    {"name": "Algeria", "alpha-3": "DZA"},
    {"name": "Andorra", "alpha-3": "AND"},
    {"name": "Angola", "alpha-3": "AGO"},
    {"name": "Argentina", "alpha-3": "ARG"},
    {"name": "Armenia", "alpha-3": "ARM"},
    {"name": "Australia", "alpha-3": "AUS"},
    {"name": "Austria", "alpha-3": "AUT"},
    {"name": "Azerbaijan", "alpha-3": "AZE"},
    {"name": "Bahamas", "alpha-3": "BHS"},
    {"name": "Bahrain", "alpha-3": "BHR"},
    {"name": "Bangladesh", "alpha-3": "BGD"},
    {"name": "Barbados", "alpha-3": "BRB"},
    {"name": "Belarus", "alpha-3": "BLR"},
    {"name": "Belgium", "alpha-3": "BEL"},
    {"name": "Belize", "alpha-3": "BLZ"},
    {"name": "Benin", "alpha-3": "BEN"},
    {"name": "Bhutan", "alpha-3": "BTN"},
    {"name": "Bolivia", "alpha-3": "BOL"},
    {"name": "Bosnia and Herzegovina", "alpha-3": "BIH"},
    {"name": "Botswana", "alpha-3": "BWA"},
    {"name": "Brazil", "alpha-3": "BRA"},
    {"name": "Brunei Darussalam", "alpha-3": "BRN"},
    {"name": "Bulgaria", "alpha-3": "BGR"},
    {"name": "Burkina Faso", "alpha-3": "BFA"},
    {"name": "Burundi", "alpha-3": "BDI"},
    {"name": "Cabo Verde", "alpha-3": "CPV"},
    {"name": "Cambodia", "alpha-3": "KHM"},
    {"name": "Cameroon", "alpha-3": "CMR"},
    {"name": "Canada", "alpha-3": "CAN"},
    {"name": "Central African Republic", "alpha-3": "CAF"},
    {"name": "Chad", "alpha-3": "TCD"},
    {"name": "Chile", "alpha-3": "CHL"},
    {"name": "China", "alpha-3": "CHN"},
    {"name": "Colombia", "alpha-3": "COL"},
    {"name": "Comoros", "alpha-3": "COM"},
    {"name": "Congo", "alpha-3": "COG"},
    {"name": "Congo (Democratic Republic of the)", "alpha-3": "COD"},
    {"name": "Costa Rica", "alpha-3": "CRI"},
    {"name": "Croatia", "alpha-3": "HRV"},
    {"name": "Cuba", "alpha-3": "CUB"},
    {"name": "Cyprus", "alpha-3": "CYP"},
    {"name": "Czechia", "alpha-3": "CZE"},
    {"name": "Denmark", "alpha-3": "DNK"},
    {"name": "Djibouti", "alpha-3": "DJI"},
    {"name": "Dominica", "alpha-3": "DMA"},
    {"name": "Dominican Republic", "alpha-3": "DOM"},
    {"name": "Ecuador", "alpha-3": "ECU"},
    {"name": "Egypt", "alpha-3": "EGY"},
    {"name": "El Salvador", "alpha-3": "SLV"},
    {"name": "Equatorial Guinea", "alpha-3": "GNQ"},
    {"name": "Eritrea", "alpha-3": "ERI"},
    {"name": "Estonia", "alpha-3": "EST"},
    {"name": "Eswatini", "alpha-3": "SWZ"},
    {"name": "Ethiopia", "alpha-3": "ETH"},
    {"name": "Fiji", "alpha-3": "FJI"},
    {"name": "Finland", "alpha-3": "FIN"},
    {"name": "France", "alpha-3": "FRA"},
    {"name": "Gabon", "alpha-3": "GAB"},
    {"name": "Gambia", "alpha-3": "GMB"},
    {"name": "Georgia", "alpha-3": "GEO"},
    {"name": "Germany", "alpha-3": "DEU"},
    {"name": "Ghana", "alpha-3": "GHA"},
    {"name": "Greece", "alpha-3": "GRC"},
    {"name": "Grenada", "alpha-3": "GRD"},
    {"name": "Guatemala", "alpha-3": "GTM"},
    {"name": "Guinea", "alpha-3": "GIN"},
    {"name": "Guinea-Bissau", "alpha-3": "GNB"},
    {"name": "Guyana", "alpha-3": "GUY"},
    {"name": "Haiti", "alpha-3": "HTI"},
    {"name": "Honduras", "alpha-3": "HND"},
    {"name": "Hungary", "alpha-3": "HUN"},
    {"name": "Iceland", "alpha-3": "ISL"},
    {"name": "India", "alpha-3": "IND"},
    {"name": "Indonesia", "alpha-3": "IDN"},
    {"name": "Iran", "alpha-3": "IRN"},
    {"name": "Iraq", "alpha-3": "IRQ"},
    {"name": "Ireland", "alpha-3": "IRL"},
    {"name": "Israel", "alpha-3": "ISR"},
    {"name": "Italy", "alpha-3": "ITA"},
    {"name": "Jamaica", "alpha-3": "JAM"},
    {"name": "Japan", "alpha-3": "JPN"},
    {"name": "Jordan", "alpha-3": "JOR"},
    {"name": "Kazakhstan", "alpha-3": "KAZ"},
    {"name": "Kenya", "alpha-3": "KEN"},
    {"name": "Kiribati", "alpha-3": "KIR"},
    {"name": "Korea (North)", "alpha-3": "PRK"},
    {"name": "Korea (South)", "alpha-3": "KOR"},
    {"name": "Kuwait", "alpha-3": "KWT"},
    {"name": "Kyrgyzstan", "alpha-3": "KGZ"},
    {"name": "Laos", "alpha-3": "LAO"},
    {"name": "Latvia", "alpha-3": "LVA"},
    {"name": "Lebanon", "alpha-3": "LBN"},
    {"name": "Lesotho", "alpha-3": "LSO"},
    {"name": "Liberia", "alpha-3": "LBR"},
    {"name": "Libya", "alpha-3": "LBY"},
    {"name": "Liechtenstein", "alpha-3": "LIE"},
    {"name": "Lithuania", "alpha-3": "LTU"},
    {"name": "Luxembourg", "alpha-3": "LUX"},
    {"name": "Madagascar", "alpha-3": "MDG"},
    {"name": "Malawi", "alpha-3": "MWI"},
    {"name": "Malaysia", "alpha-3": "MYS"},
    {"name": "Maldives", "alpha-3": "MDV"},
    {"name": "Mali", "alpha-3": "MLI"},
    {"name": "Malta", "alpha-3": "MLT"},
    {"name": "Marshall Islands", "alpha-3": "MHL"},
    {"name": "Mauritania", "alpha-3": "MRT"},
    {"name": "Mauritius", "alpha-3": "MUS"},
    {"name": "Mexico", "alpha-3": "MEX"},
    {"name": "Micronesia", "alpha-3": "FSM"},
    {"name": "Moldova", "alpha-3": "MDA"},
    {"name": "Monaco", "alpha-3": "MCO"},
    {"name": "Mongolia", "alpha-3": "MNG"},
    {"name": "Montenegro", "alpha-3": "MNE"},
    {"name": "Morocco", "alpha-3": "MAR"},
    {"name": "Mozambique", "alpha-3": "MOZ"},
    {"name": "Myanmar", "alpha-3": "MMR"},
    {"name": "Namibia", "alpha-3": "NAM"},
    {"name": "Nauru", "alpha-3": "NRU"},
    {"name": "Nepal", "alpha-3": "NPL"},
    {"name": "Netherlands", "alpha-3": "NLD"},
    {"name": "New Zealand", "alpha-3": "NZL"},
    {"name": "Nicaragua", "alpha-3": "NIC"},
    {"name": "Niger", "alpha-3": "NER"},
    {"name": "Nigeria", "alpha-3": "NGA"},
    {"name": "North Macedonia", "alpha-3": "MKD"},
    {"name": "Norway", "alpha-3": "NOR"},
    {"name": "Oman", "alpha-3": "OMN"},
    {"name": "Pakistan", "alpha-3": "PAK"},
    {"name": "Palau", "alpha-3": "PLW"},
    {"name": "Panama", "alpha-3": "PAN"},
    {"name": "Papua New Guinea", "alpha-3": "PNG"},
    {"name": "Paraguay", "alpha-3": "PRY"},
    {"name": "Peru", "alpha-3": "PER"},
    {"name": "Philippines", "alpha-3": "PHL"},
    {"name": "Poland", "alpha-3": "POL"},
    {"name": "Portugal", "alpha-3": "PRT"},
    {"name": "Qatar", "alpha-3": "QAT"},
    {"name": "Romania", "alpha-3": "ROU"},
    {"name": "Russia", "alpha-3": "RUS"},
    {"name": "Rwanda", "alpha-3": "RWA"},
    {"name": "Saint Kitts and Nevis", "alpha-3": "KNA"},
    {"name": "Saint Lucia", "alpha-3": "LCA"},
    {"name": "Saint Vincent and the Grenadines", "alpha-3": "VCT"},
    {"name": "Samoa", "alpha-3": "WSM"},
    {"name": "San Marino", "alpha-3": "SMR"},
    {"name": "Sao Tome and Principe", "alpha-3": "STP"},
    {"name": "Saudi Arabia", "alpha-3": "SAU"},
    {"name": "Senegal", "alpha-3": "SEN"},
    {"name": "Serbia", "alpha-3": "SRB"},
    {"name": "Seychelles", "alpha-3": "SYC"},
    {"name": "Sierra Leone", "alpha-3": "SLE"},
    {"name": "Singapore", "alpha-3": "SGP"},
    {"name": "Slovakia", "alpha-3": "SVK"},
    {"name": "Slovenia", "alpha-3": "SVN"},
    {"name": "Solomon Islands", "alpha-3": "SLB"},
    {"name": "Somalia", "alpha-3": "SOM"},
    {"name": "South Africa", "alpha-3": "ZAF"},
    {"name": "South Sudan", "alpha-3": "SSD"},
    {"name": "Spain", "alpha-3": "ESP"},
    {"name": "Sri Lanka", "alpha-3": "LKA"},
    {"name": "Sudan", "alpha-3": "SDN"},
    {"name": "Suriname", "alpha-3": "SUR"},
    {"name": "Sweden", "alpha-3": "SWE"},
    {"name": "Switzerland", "alpha-3": "CHE"},
    {"name": "Syria", "alpha-3": "SYR"},
    {"name": "Taiwan", "alpha-3": "TWN"},
    {"name": "Tajikistan", "alpha-3": "TJK"},
    {"name": "Tanzania", "alpha-3": "TZA"},
    {"name": "Thailand", "alpha-3": "THA"},
    {"name": "Timor-Leste", "alpha-3": "TLS"},
    {"name": "Togo", "alpha-3": "TGO"},
    {"name": "Tonga", "alpha-3": "TON"},
    {"name": "Trinidad and Tobago", "alpha-3": "TTO"},
    {"name": "Tunisia", "alpha-3": "TUN"},
    {"name": "Turkey", "alpha-3": "TUR"},
    {"name": "Turkmenistan", "alpha-3": "TKM"},
    {"name": "Tuvalu", "alpha-3": "TUV"},
    {"name": "Uganda", "alpha-3": "UGA"},
    {"name": "Ukraine", "alpha-3": "UKR"},
    {"name": "United Arab Emirates", "alpha-3": "ARE"},
    {"name": "United Kingdom", "alpha-3": "GBR"},
    {"name": "United States of America", "alpha-3": "USA"},
    {"name": "Uruguay", "alpha-3": "URY"},
    {"name": "Uzbekistan", "alpha-3": "UZB"},
    {"name": "Vanuatu", "alpha-3": "VUT"},
    {"name": "Vatican City", "alpha-3": "VAT"},
    {"name": "Venezuela", "alpha-3": "VEN"},
    {"name": "Vietnam", "alpha-3": "VNM"},
    {"name": "Yemen", "alpha-3": "YEM"},
    {"name": "Zambia", "alpha-3": "ZMB"},
    {"name": "Zimbabwe", "alpha-3": "ZWE"}
]
